package com.spring.boot.data.concepts.jpa_advanced.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@Entity
@Data
@Table(name = "course_table")
// @NoArgsConstructor // this is mandatory to have to allow Jpa to create "Course" bean
public class Course {
    @Id
    @GeneratedValue // primary key automatically generated by Jpa
    @Column(name = "course_id")
    private Long id;

    @Column(name = "course_name", nullable = false, unique = true)
    @NonNull // lombok annotation for bean
    private String name;

     // this no args constructor 
    //  is mandatory to have to allow Jpa to create "Course" bean
    // 'protected' will ensure that classes that don't inherit from course, cant create its constructor
    protected Course(){ 

    }

    @Override
    public String toString(){
            return String.format("Course id : %s, Course name : %s", this.id, this.name);
        }

}
